title: Sander Voerman
email: sander@redesigningpsychiatry.org
description: Personal page of Sander Voerman
show_excerpts: false
url: "https://www.savoerman.nl"

# Minima 3.x
minima:
  date_format: "%b %-d, %Y"

  social_links:
    github: sandervoerman
    linkedin: savoerman
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - books.md
 - articles.md
 - projects.md

# Build settings
markdown: kramdown
remote_theme: sandervoerman/jesuis
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - README.md
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
